AntiCorruptionManagementSystem/Controllers/InvestigationWorkProgressesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AntiCorruptionManagementSystem.Models;

namespace AntiCorruptionManagementSystem.Controllers
{
    public class InvestigationWorkProgressesController : Controller
    {
        private AcmsDbContext _db = new AcmsDbContext();

        public ActionResult InvestigationProgressReport()
        {
            List<InvestigationWorkProgress> progressList = new List<InvestigationWorkProgress>();
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name");
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name");
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name");
            return View(progressList);
        }
        public ActionResult InvestigationProgressReportView(int? employeeId, int? wingId, int? sajekaId)
        {
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name");
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name");
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name");
            ViewBag.WingName = _db.Wing.Where(i => i.Sl == wingId).Select(p => p.Name).FirstOrDefault();
            ViewBag.SajekaName = _db.Sajeka.Where(i => i.Sl == sajekaId).Select(p => p.Name).FirstOrDefault();
            ViewBag.EmployeeName = _db.Employee.Where(i => i.Sl == employeeId).Select(p => p.Name).FirstOrDefault();
            List<InvestigationWorkProgress> progressList = _db.InvestigationWorkProgress.Where(t => t.EmployeeId == employeeId).Where(t=> t.WingId==wingId).Where(t => t.SajekaId == sajekaId).Include(x => x.Sajekas).Include(x => x.Wings).Include(x => x.Employees).ToList();
            var progressDate = _db.InvestigationWorkProgress.Select(t => t.DateofInvestigateOrder).FirstOrDefault();
            var halfProgressDate = progressDate.AddDays(15);
            ViewBag.halfProgressDate = halfProgressDate;
            var fullProgressDate = progressDate.AddDays(30);
            ViewBag.fullProgressDate = fullProgressDate;
            var currentDate = DateTime.Now;
            ViewBag.halfmonthCount = Math.Floor((halfProgressDate - currentDate).TotalDays);
            ViewBag.fullmonthCount = Math.Floor((fullProgressDate- currentDate).TotalDays);
            ViewBag.Status = "SelectEmployee";
            return View("InvestigationProgressReport", progressList);
        }

        // GET: InvestigationWorkProgresses
        public ActionResult Index()
        {
            var investigationWorkProgress = _db.InvestigationWorkProgress.Include(i => i.Accusers).Include(i => i.Employees).Include(i => i.Sajekas).Include(i => i.Wings);
            return View(investigationWorkProgress.ToList());
        }



        // GET: InvestigationWorkProgresses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvestigationWorkProgress investigationWorkProgress = _db.InvestigationWorkProgress.Find(id);
            if (investigationWorkProgress == null)
            {
                return HttpNotFound();
            }
            return View(investigationWorkProgress);
        }

        // GET: InvestigationWorkProgresses/Create
        public ActionResult Create()
        {
            ViewBag.AccuserId = new SelectList(_db.Accuser, "Sl", "Name");
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name");
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name");
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name");
            return View();
        }

        // POST: InvestigationWorkProgresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,FileNumber,DateofInvestigateOrder,ComplainDescription,CurrentStatus,Remarks,IsActive,AccuserId,WingId,SajekaId,EmployeeId")] InvestigationWorkProgress investigationWorkProgress)
        {
            if (investigationWorkProgress.FileNumber!="")
            {
                investigationWorkProgress.IsActive = true;
                _db.InvestigationWorkProgress.Add(investigationWorkProgress);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccuserId = new SelectList(_db.Accuser, "Sl", "Name", investigationWorkProgress.AccuserId);
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name", investigationWorkProgress.EmployeeId);
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name", investigationWorkProgress.SajekaId);
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", investigationWorkProgress.WingId);
            return View(investigationWorkProgress);
        }

        // GET: InvestigationWorkProgresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvestigationWorkProgress investigationWorkProgress = _db.InvestigationWorkProgress.Find(id);
            if (investigationWorkProgress == null)
            {
                return HttpNotFound();
            }
            ViewBag.AccuserId = new SelectList(_db.Accuser, "Sl", "Name", investigationWorkProgress.AccuserId);
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name", investigationWorkProgress.EmployeeId);
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name", investigationWorkProgress.SajekaId);
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", investigationWorkProgress.WingId);
            return View(investigationWorkProgress);
        }

        // POST: InvestigationWorkProgresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,FileNumber,DateofInvestigateOrder,ComplainDescription,CurrentStatus,Remarks,IsActive,AccuserId,WingId,SajekaId,EmployeeId")] InvestigationWorkProgress investigationWorkProgress)
        {
            if (investigationWorkProgress.FileNumber != "")
            {
                _db.Entry(investigationWorkProgress).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccuserId = new SelectList(_db.Accuser, "Sl", "Name", investigationWorkProgress.AccuserId);
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name", investigationWorkProgress.EmployeeId);
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name", investigationWorkProgress.SajekaId);
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", investigationWorkProgress.WingId);
            return View(investigationWorkProgress);
        }

        // GET: InvestigationWorkProgresses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InvestigationWorkProgress investigationWorkProgress = _db.InvestigationWorkProgress.Find(id);
            if (investigationWorkProgress == null)
            {
                return HttpNotFound();
            }
            return View(investigationWorkProgress);
        }

        // POST: InvestigationWorkProgresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InvestigationWorkProgress investigationWorkProgress = _db.InvestigationWorkProgress.Find(id);
            if (investigationWorkProgress != null)
            {
                investigationWorkProgress.IsActive = false;
                _db.Entry(investigationWorkProgress).State = EntityState.Modified;
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiCorruptionManagementSystem/Views/InvestigationWorkProgresses/Create.cshtml
@model AntiCorruptionManagementSystem.Models.InvestigationWorkProgress

@{
    ViewBag.Title = "Create";
}

<h2>তদন্তের অগ্রগতি</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>তদন্ত অনুবিভাগের কর্মকর্তাদের কাজের অগ্রগতি</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.WingId, "প্রধান উইং", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WingId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WingId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SajekaId, "সজেকা", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SajekaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SajekaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "কর্মকর্তার নাম ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FileNumber,"ফাইলের নম্বর", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateofInvestigateOrder,"তদন্ত শুরুর জন্য পত্র/ দায়িত্ব প্রাপ্তির তারিখ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateofInvestigateOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateofInvestigateOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ComplainDescription,"অভিযোগের সংক্ষিপ্ত বিবরণ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ComplainDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ComplainDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentStatus,"বর্তমান অবস্থা (রিট/মিস কেইসের কারনে স্থগিত থাকলে উল্লেখ করুন),সাক্ষীদের সাক্ষ্য গ্রহণ প্রয়োজনীয় রেকর্ডপত্র সংগ্রহ ইত্যাদি ক্ষেত্রে কাজের অগ্রগতির শতকরা(%) হার", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Remarks,"মন্তব্য",  htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Remarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Remarks, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.AccuserId, "অভিযোগকারীর বিস্তারিত", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccuserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccuserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="নিবন্ধন" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("তালিকায় ফেরা", "Index")
</div>

AntiCorruptionManagementSystem/Views/InvestigationWorkProgresses/Delete.cshtml
@model AntiCorruptionManagementSystem.Models.InvestigationWorkProgress

@{
    ViewBag.Title = "Delete";
}

<h2>মুছুন</h2>

<h3>আপনি কি সত্যি মুছতে চান?</h3>
<div>
    <h4>তদন্ত অনুবিভাগের কর্মকর্তাদের কাজের অগ্রগতি</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            উইং এর নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wings.Name)
        </dd>

        <dt>
            সজেকার নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sajekas.Name)
        </dd>


        <dt>
            কর্মকর্তার নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employees.Name)
        </dd>

        <dt>
            অভিযোগকারীর নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Accusers.Name)
        </dd>

        <dt>
            ফাইলের নম্বর
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileNumber)
        </dd>

        <dt>
           তদন্ত শুরু করার জন্য পত্র/দায়িত্ব প্রাপ্তির তারিখ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateofInvestigateOrder)
        </dd>

        <dt>
            অভিযোগের বিবরন
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComplainDescription)
        </dd>

        <dt>
            বর্তমান অবস্থা
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentStatus)
        </dd>

        <dt>
            মন্তব্য
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        <dt>
            অ্যাকাউন্ট সচল ?
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="মুছুন" class="btn btn-default" /> |
            @Html.ActionLink("তালিকায় ফেরা", "Index")
        </div>
    }
</div>

AntiCorruptionManagementSystem/Views/InvestigationWorkProgresses/Details.cshtml
@model AntiCorruptionManagementSystem.Models.InvestigationWorkProgress

@{
    ViewBag.Title = "Details";
}

<h2>বিবরন</h2>

<div>
    <h4>তদন্ত অনুবিভাগের কর্মকর্তাদের কাজের অগ্রগতি</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            উইং এর নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wings.Name)
        </dd>

        <dt>
            সজেকার নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sajekas.Name)
        </dd>

        <dt>
            কর্মকর্তার নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employees.Name)
        </dd>

        <dt>
            অভিযোগকারীর নাম
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Accusers.Name)
        </dd>

        <dt>
            ফাইলের নম্বর
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileNumber)
        </dd>

        <dt>
            তদন্ত শুরু করার জন্য পত্র/দায়িত্ব প্রাপ্তির তারিখ
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateofInvestigateOrder)
        </dd>

        <dt>
            অভিযোগের বিবরন
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComplainDescription)
        </dd>

        <dt>
            বর্তমান অবস্থা
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentStatus)
        </dd>

        <dt>
            মন্তব্য
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Remarks)
        </dd>

        <dt>
            অ্যাকাউন্ট সচল ?
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("সম্পাদন", "Edit", new { id = Model.Sl }) |
    @Html.ActionLink("তালিকায় ফেরা", "Index")
</p>

AntiCorruptionManagementSystem/Views/InvestigationWorkProgresses/Index.cshtml
@model IEnumerable<AntiCorruptionManagementSystem.Models.InvestigationWorkProgress>

@{
    ViewBag.Title = "Index";
}

<h2>তলিকা</h2>

<p>
    @Html.ActionLink("নতুন তৈরি করুন", "Create")
</p>
<table class="table">
    <tr>
        <th>
            উইং এর নাম
        </th>
        <th>
            সজেকার নাম
        </th>
        <th>
            কর্মকর্তার নাম
        </th>
        <th>
            অভিযোগকারীর নাম 
        </th>
        <th>
           ফাইলের নম্বর
        </th>
        <th>
            তদন্ত শুরুর জন্য পত্র/ দায়িত্ব প্রাপ্তির তারিখ
        </th>
        <th>
            অভিযোগের সংক্ষিপ্ত বিবরণ
        </th>
        <th>
            বর্তমান অবস্থা
        </th>
        <th>
            মন্তব্য
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Wings.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Sajekas.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Employees.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Accusers.Name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.FileNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateofInvestigateOrder)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ComplainDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Remarks)
        </td>
        <td>
            @Html.ActionLink("সম্পাদন", "Edit", new { id=item.Sl }) |
            @Html.ActionLink("বিবরণ", "Details", new { id=item.Sl }) |
            @Html.ActionLink("মুছুন", "Delete", new { id=item.Sl })
        </td>
    </tr>
}

</table>

AntiCorruptionManagementSystem/Views/InvestigationWorkProgresses/InvestigationProgressReport.cshtml
@{
    ViewBag.Title = "Investigation";
}
<header class="panel_header">
    <h2 class="title pull-left" style="margin-left:3%">তদন্ত অনুবিভাগে কাজের অগ্রগতি</h2>
    <div class="actions panel_actions pull-right">
        <i class="box_toggle fa fa-chevron-down"></i>
    </div>
</header>
<br /> <br /><br /><br /><br />
@using (Html.BeginForm("InvestigationProgressReportView", "InvestigationWorkProgresses"))
{
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="col-md-10" style="margin-left:3%">
                <div class="form-group">
                    <label class="form-label" for="wingId">প্রধান উইং:</label>
                    <div class="controls">
                        @Html.DropDownList("WingId", null, "--প্রধান উইং এর নাম পছন্দ করুন--", htmlAttributes: new { @class = "form-control", style = "width:100%", @name = "WingName" })
                    </div>
                </div>

            </div>
            <div class="col-md-10" style="margin-left:3%">
                <div class="form-group">
                    <label class="form-label" for="sajekaId">উইং এর নাম:</label>
                    <div class="controls">
                        @Html.DropDownList("SajekaId", null, "--উইং এর নাম পছন্দ করুন--", htmlAttributes: new { @class = "form-control", style = "width:100%", @name = "SajekaName" })
                    </div>
                </div>

            </div>
            <div class="col-md-10" style="margin-left:3%">
                <div class="form-group">
                    <label class="form-label" for="employeeId">কর্মকর্তার নাম:</label>
                    <div class="controls">
                        @Html.DropDownList("EmployeeId", null, "--কর্মকর্তার নাম পছন্দ করুন--", htmlAttributes: new { @class = "form-control", style = "width:100%", @name = "EmployeeName" })
                    </div>
                </div>

            </div>
        </div>
        <div class="col-md-4"></div>
       
        <div class="col-xs-2" style="margin-left:44%">
            <button type="submit" class="btn btn-success">দেখুন</button>
        </div>
    </div>
    <br /><br /><br />

    <div class="content-body">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="table-responsive" data-pattern="priority-columns">
                    @if (Model.Count > 0)
                    {
                        if (ViewBag.Status != null)
                        {
                           

                            <table cellspacing="0" id="tech-companies-1" class="table table-small-font table-bordered table-striped">

                                <thead>
                                    <tr>
                                        <th>অনুসন্ধান শুরুর তারিখ</th>
                                        <th> উইং এর নাম</th>
                                        <th>কর্মকর্তার নাম</th>
                                        <th>ফাইল নম্বর</th>
                                        <th>অভিযোগকারীর নাম</th>

                                        <th>মামলার বিস্তারিত</th>
                                        <th>মামলার বর্তমান অবস্থা</th>
                                        <th>১৫ কর্মদিবস উত্তীর্ণের তারিখ</th>
                                        <th>১৫ কর্মদিবস উত্তীর্ণ হতে লাগবে</th>
                                        <th>৩০ কর্মদিবস উত্তীর্ণের তারিখ</th>
                                        <th>৩০ কর্মদিবস উত্তীর্ণ হতে লাগবে</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        @for (int i = 0; i < Model.Count; i++)
                                        {

                                            <td>@Model[i].DateofInvestigateOrder.ToString("dd-MM-yyyy")</td>
                                            <td>@Model[i].Sajekas.Name</td>
                                            <td>@Model[i].Employees.Name</td>
                                            <td>@Model[i].FileNumber</td>
                                            <td>@Model[i].Accusers.Name</td>
                                            <td>@Model[i].ComplainDescription</td>
                                            <td>@Model[i].CurrentStatus</td>

                                        }
                                        <td style="background-color:#00FF00;">
                                            @ViewBag.halfProgressDate.ToString("dd-MM-yyyy")
                                        </td>
                                        <td>
                                            @ViewBag.halfmonthCount
                                        </td>
                                        <td style="background-color:#FF0000;">
                                            @ViewBag.fullProgressDate.ToString("dd-MM-yyyy")
                                        </td>
                                        <td>
                                            @ViewBag.fullmonthCount
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
}