AntiCorruptionManagementSystem/Controllers/AccusersController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AntiCorruptionManagementSystem.Models;

namespace AntiCorruptionManagementSystem.Controllers
{
    public class AccusersController : Controller
    {
        private AcmsDbContext _db = new AcmsDbContext();

        // GET: Accusers
        public ActionResult Index()
        {
            return View(_db.Accuser.ToList());
        }

        // GET: Accusers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accuser accuser = _db.Accuser.Find(id);
            if (accuser == null)
            {
                return HttpNotFound();
            }
            return View(accuser);
        }

        // GET: Accusers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Accusers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,Name,IsActive")] Accuser accuser)
        {
            if (accuser.Name!= "")
            {
                accuser.IsActive = true;
                _db.Accuser.Add(accuser);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(accuser);
        }

        // GET: Accusers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accuser accuser = _db.Accuser.Find(id);
            if (accuser == null)
            {
                return HttpNotFound();
            }
            return View(accuser);
        }

        // POST: Accusers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,Name,IsActive")] Accuser accuser)
        {
            if (accuser.Name != "")
            {
                _db.Entry(accuser).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(accuser);
        }

        // GET: Accusers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Accuser accuser = _db.Accuser.Find(id);
            if (accuser == null)
            {
                return HttpNotFound();
            }
            return View(accuser);
        }

        // POST: Accusers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Accuser accuser = _db.Accuser.Find(id);
            accuser.IsActive = false;
            _db.Entry(accuser).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiCorruptionManagementSystem/Controllers/CasesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AntiCorruptionManagementSystem.Models;

namespace AntiCorruptionManagementSystem.Controllers
{
    public class CasesController : Controller
    {
        private AcmsDbContext _db = new AcmsDbContext();

        // GET: Cases
        public ActionResult Index()
        {
            var caseList = _db.Case.Include(e => e.Employees).Include(e => e.Sajekas).Include(e => e.Wings);
            return View(caseList.ToList());
        }

        // GET: Cases/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case cases = _db.Case.Find(id);
            if (cases == null)
            {
                return HttpNotFound();
            }
            return View(cases);
        }

        // GET: Cases/Create
        public ActionResult Create()
        {
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name");
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name");
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name");
            return View();
        }

        // POST: Cases/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,CaseNumber,CaseDate,Description,DateofIOTaken,ProgressDetails,Remarks,IsActive,WingId,SajekaId,EmployeeId")] Case cases)
        {
            if (cases.CaseNumber!="")
            {
                cases.IsActive = true;
                _db.Case.Add(cases);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name", cases.EmployeeId);
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name", cases.SajekaId);
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", cases.WingId);
            return View(cases);
        }

        // GET: Cases/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case cases = _db.Case.Find(id);
            if (cases == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name", cases.EmployeeId);
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name", cases.SajekaId);
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", cases.WingId);
            return View(cases);
        }

        // POST: Cases/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,CaseNumber,CaseDate,Description,DateofIOTaken,ProgressDetails,Remarks,IsActive,WingId,SajekaId,EmployeeId")] Case cases)
        {
            if (cases.CaseNumber != "")
            {
                _db.Entry(cases).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeId = new SelectList(_db.Employee, "Sl", "Name", cases.EmployeeId);
            ViewBag.SajekaId = new SelectList(_db.Sajeka, "Sl", "Name", cases.SajekaId);
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", cases.WingId);
            return View(cases);
        }

        // GET: Cases/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Case cases = _db.Case.Find(id);
            if (cases == null)
            {
                return HttpNotFound();
            }
            return View(cases);
        }

        // POST: Cases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Case cases = _db.Case.Find(id);
            cases.IsActive = false;
            _db.Entry(cases).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiCorruptionManagementSystem/Controllers/SajekasController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AntiCorruptionManagementSystem.Models;

namespace AntiCorruptionManagementSystem.Controllers
{
    public class SajekasController : Controller
    {
        private AcmsDbContext _db = new AcmsDbContext();

        // GET: Sajekas
        public ActionResult Index()
        {
            return View(_db.Sajeka.Include(i=> i.Wings).ToList());
        }

        // GET: Sajekas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sajeka sajeka = _db.Sajeka.Find(id);
            if (sajeka == null)
            {
                return HttpNotFound();
            }
            return View(sajeka);
        }

        // GET: Sajekas/Create
        public ActionResult Create()
        {
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name");
            return View();
        }

        // POST: Sajekas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,WingId,Name")] Sajeka sajeka)
        {
            if (ModelState.IsValid)
            {
                _db.Sajeka.Add(sajeka);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name",sajeka.WingId);
            return View(sajeka);
        }

        // GET: Sajekas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sajeka sajeka = _db.Sajeka.Find(id);
            if (sajeka == null)
            {
                return HttpNotFound();
            }
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", sajeka.WingId);
            return View(sajeka);
        }

        // POST: Sajekas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,WingId,Name")] Sajeka sajeka)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(sajeka).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.WingId = new SelectList(_db.Wing, "Sl", "Name", sajeka.WingId);
            return View(sajeka);
        }

        // GET: Sajekas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sajeka sajeka = _db.Sajeka.Find(id);
            if (sajeka == null)
            {
                return HttpNotFound();
            }
            return View(sajeka);
        }

        // POST: Sajekas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sajeka sajeka = _db.Sajeka.Find(id);
            _db.Sajeka.Remove(sajeka);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiCorruptionManagementSystem/Controllers/WingsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AntiCorruptionManagementSystem.Models;

namespace AntiCorruptionManagementSystem.Controllers
{
    public class WingsController : Controller
    {
        private AcmsDbContext _db = new AcmsDbContext();

        // GET: Wings
        public ActionResult Index()
        {
            return View(_db.Wing.ToList());
        }

        // GET: Wings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wing wing = _db.Wing.Find(id);
            if (wing == null)
            {
                return HttpNotFound();
            }
            return View(wing);
        }

        // GET: Wings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Wings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Sl,Name")] Wing wing)
        {
            if (ModelState.IsValid)
            {
                _db.Wing.Add(wing);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(wing);
        }

        // GET: Wings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wing wing = _db.Wing.Find(id);
            if (wing == null)
            {
                return HttpNotFound();
            }
            return View(wing);
        }

        // POST: Wings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Sl,Name")] Wing wing)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(wing).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(wing);
        }

        // GET: Wings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wing wing = _db.Wing.Find(id);
            if (wing == null)
            {
                return HttpNotFound();
            }
            return View(wing);
        }

        // POST: Wings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wing wing = _db.Wing.Find(id);
            _db.Wing.Remove(wing);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AntiCorruptionManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="~/Resource/acc_logo.ico" />
    <title>@ViewBag.Title - Anti Corruption Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("দুর্নীতি দমন কমিশন", "Index", "Wings", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("উইং", "Index", "Wings")</li>
                    <li>@Html.ActionLink("সজেকা", "Index", "Sajekas")</li>
                    <li>@Html.ActionLink("কর্মকর্তা", "Index", "Employees")</li>
                    <li>@Html.ActionLink("মামলা", "Index", "Cases")</li>
                    <li>@Html.ActionLink("মামলার অভিযোগ", "Index", "CaseObjections")</li>
                    <li>@Html.ActionLink("তদন্তাধীন মামলার আসামি", "Index", "AccusedPersonInfoes")</li>
                    <li>@Html.ActionLink("অভিযোগকারীর তথ্য", "Index", "Accusers")</li>
                    <li>@Html.ActionLink("অনুসন্ধান অনুবিভাগ", "Index", "InquiryWorkProgresses")</li>
                    <li>@Html.ActionLink("তদন্ত অনুবিভাগ", "Index", "InvestigationWorkProgresses")</li>
                    <li>@Html.ActionLink("তদন্ত অনুবিভাগ রিপোর্ট", "InvestigationProgressReport", "InvestigationWorkProgresses")</li>
                    <li>@Html.ActionLink("অনুসন্ধান অনুবিভাগ রিপোর্ট", "InquiryProgressReport", "InquiryWorkProgresses")</li>*@
                    <li><img class="img-responsive2" src="~/Resource/acc_logoShort.png"></li>
                    <li>@Html.ActionLink("ড্যাশবোর্ড", "Index", "Home")</li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">প্রাথমিক নিবন্ধন</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("উইং নিবন্ধন", "Create", "Wings")</li>
                            <li>@Html.ActionLink("উইং প্রতিবেদন", "Index", "Wings")</li>
                            <li>@Html.ActionLink("সজেকা নিবন্ধন", "Create", "Sajekas")</li>
                            <li>@Html.ActionLink("সজেকা প্রতিবেদন", "Index", "Sajekas")</li>
                            <li>@Html.ActionLink("কর্মকর্তা নিবন্ধন", "Create", "Employees")</li>
                            <li>@Html.ActionLink("কর্মকর্তা প্রতিবেদন", "Index", "Employees")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">প্রধান নিবন্ধন</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("মামলা নিবন্ধন", "Create", "Cases")</li>
                            <li>@Html.ActionLink("মামলা প্রতিবেদন", "Index", "Cases")</li>
                            <li>@Html.ActionLink("মামলার অভিযোগ নিবন্ধন", "Create", "CaseObjections")</li>
                            <li>@Html.ActionLink("মামলার অভিযোগ প্রতিবেদন", "Index", "CaseObjections")</li>
                            <li>@Html.ActionLink("অভিযোগকারী নিবন্ধন", "Create", "Accusers")</li>
                            <li>@Html.ActionLink("অভিযোগকারীর তথ্য", "Index", "Accusers")</li>
                            <li>@Html.ActionLink("তদন্তাধীন মামলার আসামি নিবন্ধন", "Create", "AccusedPersonInfoes")</li>
                            <li>@Html.ActionLink("তদন্তাধীন মামলার আসামি প্রতিবেদন", "Index", "AccusedPersonInfoes")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">কাজের অগ্রগতি</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("অনুসন্ধান অনুবিভাগের কাজের অগ্রগতি নিবন্ধন", "Create", "InquiryWorkProgresses")</li>
                            <li>@Html.ActionLink("অনুসন্ধান অনুবিভাগের কাজের অগ্রগতি প্রতিবেদন", "Index", "InquiryWorkProgresses")</li>
                            <li>@Html.ActionLink("তদন্ত অনুবিভাগের কাজের অগ্রগতি নিবন্ধন", "Create", "InvestigationWorkProgresses")</li>
                            <li>@Html.ActionLink("তদন্ত অনুবিভাগের কাজের অগ্রগতি প্রতিবেদন", "Index", "InvestigationWorkProgresses")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">প্রতিবেদন</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("তদন্ত অনুবিভাগ রিপোর্ট", "InvestigationProgressReport", "InvestigationWorkProgresses")</li>
                            <li>@Html.ActionLink("অনুসন্ধান অনুবিভাগ রিপোর্ট", "InquiryProgressReport", "InquiryWorkProgresses")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
        <center>
            
            <footer style="margin-top:38%">
                <hr />
                <p>&copy; @DateTime.Now.Year - দুর্নীতি দমন কমিশন . Powered by <a url="http://futuristictech.xyz/" target="_blank">Futuristic Technologies LTD</a></p>
            </footer>
        </center>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>